avoid erroring when nonexistent paths are in default PATH

diff --git a/bin/checkPath b/bin/checkPath
--- a/bin/checkPath
+++ b/bin/checkPath
@@ -5,10 +5,12 @@ has() { type -p "$1" > /dev/null; }
 paths=$(echo "$1" | sed "s/:/\n/g")
 
 for i in $paths ; do
-    for j in $(find "$i" -maxdepth 1 -type f -executable -printf "%f\n") ; do
-        if ! has "$j" ; then
-            printf '\033[31mWARNING: missing %s\n' "$j"
-        fi
-    done
+    if [ -d "$i" ] ; then
+        for j in $(find "$i" -maxdepth 1 -type f -executable -printf "%f\n") ; do
+            if ! has "$j" ; then
+                printf '\033[31mWARNING: missing \"%s\" (%s) from default PATH\033[39m\n' "$j" "$i/$j"
+            fi
+        done
+    fi
 done
 
