rewrite update in bash

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,195 +1,139 @@
-#!/usr/bin/env python3
-"""update: a script to automatically update software"""
+#!/usr/bin/env bash
+# update: a script to automatically update software
 
-from shutil import which
-from os import environ
-from subprocess import run
-import sys
-import argparse
+# Check if specified program is in PATH
+has() { type -p "$1" > /dev/null; }
 
-def is_termux() -> bool:
-    """Check if current os is termux"""
-    return environ.get("TERMUX_VERSION", None) is not None
+contains() {
+    local value="$1"
+    shift
+    local item
+    for item in "$@"; do
+        [ "$item" = "$value" ] && return 0
+    done
+    return 1
+}
 
-def has(program: str) -> bool:
-    """Check if specified program is in PATH"""
-    return which(program) is not None
+#TODO: Returns True if terminal supports color
+SUPPORTS_COLOR=true
 
-def supports_color():
-    """Returns True if terminal supports color"""
-    return hasattr(sys.stdout, 'isatty') and sys.stdout.isatty() and sys.platform != "win32"
+#Prints the specified string in green (if possible) prefixed with 'OK: '
+ok() {
+    if $SUPPORTS_COLOR ; then
+        printf "\033[92mOK: %s\033[0m\n" "$1"
+    else
+        printf "OK: %s\n" "$1"
+    fi
+}
 
-def ok(string: str):
-    """Prints the specified string in green (if possible) prefixed with 'OK: '"""
-    if supports_color():
-        print(f"\033[92mOK: {string}\033[0m")
-    else:
-        print(f"OK: {string}")
+#Prints the specified string in yellow (if possible) prefixed with 'WARN: '
+warn() {
+    if $SUPPORTS_COLOR ; then
+        printf "\033[93mWARN: %s\033[0m\n" "$1"
+    else
+        printf "WARN: %s\n" "$1"
+    fi
+}
 
-def warn(string: str):
-    """Prints the specified string in yellow (if possible) prefixed with 'WARN: '"""
-    if supports_color():
-        print(f"\033[93mWARN: {string}\033[0m")
-    else:
-        print(f"WARN: {string}")
+#Prints the specified string in red (if possible) prefixed with 'ERROR: ' and exits with code 1
+error() {
+    if $SUPPORTS_COLOR ; then
+        printf "\033[91mERROR: %s\033[0m\n" "$1"
+    else
+        printf "ERROR: %s\n" "$1"
+    fi
+    exit 1
+}
 
-def error(string: str):
-    """Prints the specified string in red (if possible) prefixed with 'ERROR: ' and exits with code 1"""
-    if supports_color():
-        print(f"\033[91mERROR: {string}\033[0m")
-    else:
-        print(f"ERROR: {string}")
-    sys.exit(1)
+ROOT_STRING=""
+if [ -n "$TERMUX_VERSION" ] ; then
+    ok "No Root Privileges on Termux"
+elif [ $EUID -eq 0 ] ; then
+    true
+elif has doas ; then
+    ROOT_STRING="doas"
+elif has sudo ; then
+    ROOT_STRING="sudo"
+else
+    error "no root privileges found.\nYou can try running this script as root or verifying that sudo or doas is in your PATH"
+fi
 
-root_string = None
-if is_termux():
-    ok("No Root Privileges on Termux")
-    root_string = ""
-elif environ.get("EUID", None) == 0:
-    root_string = ""
-elif has("doas"):
-    root_string = "doas"
-elif has("sudo"):
-    root_string = "sudo"
-else:
-    #Ideally we would just skip managers which need root access here
-    error("ERROR: no root privileges found.\nYou can try running this script as root or verifying that sudo or doas is in your PATH")
-ok(f"Using '{root_string}' as root prefix")
+ok "Using '$ROOT_STRING' as root prefix"
 
-class PkgManager:
-    """PkgManager houses basic info needed to update a package manager"""
-    def __init__(self, name: str, root: bool, cmds: list[list[str]]):
-        self.name = name
-        self.root = root
-        self.cmds = cmds
-    def get_name(self):
-        """Returns the name of the PkgManager's binary"""
-        return self.name
-    def uses_root(self):
-        """Returns true if the PkgManager should be run as root"""
-        return self.root
-    def get_cmds(self):
-        """Returns a list of paramater lists to run in order to update the PkgManager"""
-        return self.cmds
+declare -A MANAGER_LIST
+MANAGER_LIST["apt-get"]="$ROOT_STRING apt-get update &&
+                         $ROOT_STRING apt-get upgrade &&
+                         $ROOT_STRING apt-get autoremove"
+MANAGER_LIST["brew"]="brew update &&
+                      brew upgrade &&
+                      brew autoremove"
+MANAGER_LIST["dnf"]="$ROOT_STRING dnf upgrade"
+MANAGER_LIST["dfm"]="dfm update &&
+                     dfm upgrade"
+MANAGER_LIST["emerge"]="$ROOT_STRING emerge --sync &&
+                        $ROOT_STRING emerge --update --deep --with-bdeps=y @world &&
+                        $ROOT_STRING emerge --deepclean"
+MANAGER_LIST["flatpak"]="$ROOT_STRING flatpak update"
+MANAGER_LIST["softwareupdate"]="softwareupdate --verbose -lir --agree-to-license"
+MANAGER_LIST["nvim"]="nvim --headless -c \"lua if vim.pack then vim.pack.update() end\" -c qa && echo"
+MANAGER_LIST["pacman"]="$ROOT_STRING pacman -Syu"
+MANAGER_LIST["pkg"]="pkg upgrade &&
+                     pkg autoclean"
+MANAGER_LIST["port"]="port -v selfupdate &&
+                      port -v upgrade outdated &&
+                      port -v uninstall inactive"
+MANAGER_LIST["scoop"]="scoop update"
+MANAGER_LIST["snap"]="$ROOT_STRING snap refresh"
+MANAGER_LIST["tldr"]="tldr -u"
+MANAGER_LIST["yay"]="yay -Syu --noconfirm"
 
-def get_home() -> str:
-    """return the current users home directory, with a trailing slash"""
-    home = environ.get("HOME")
-    if home[-1] != "/":
-        home += "/"
-    return home
+toUpdate=("${!MANAGER_LIST[@]}")
+listMode=false
+toSkip=()
 
-def get_managers() -> None:
-    """returns a list of all availible package managers"""
-    found_managers = []
-    for pkg_manager in MANAGER_LIST:
-        if has(pkg_manager.get_name()):
-            found_managers.append(pkg_manager.get_name())
-    return found_managers
+while [ $# -gt 0 ] ; do
+    case "$1" in
+        -u|--update)
+            shift
+            toUpdate=()
+            while [ $# -gt 0 ] && [ "${1:0:1}" != "-" ] ; do
+                toUpdate+=("$1")
+                shift
+            done
+            ;;
+        -s|--skip)
+            shift
+            toSkip=()
+            while [ $# -gt 0 ] && [ "${1:0:1}" != "-" ] ; do
+                toSkip+=("$1")
+                shift
+            done
+            ;;
+        -l|--list)
+            listMode=true
+            shift
+            ;;
+        *)
+            shift
+            ;;
+    esac
+done
 
-def update(mgr: PkgManager) -> None:
-    """update a specified package manager"""
-    if has(mgr.get_name()):
-        if mgr.uses_root() and mgr.uses_root() != "":
-            for cmd in mgr.get_cmds():
-                run([root_string, *cmd], check=False)
-        else:
-            for cmd in mgr.get_cmds():
-                run(cmd, check=False)
+if $listMode ; then
+    printf "Managers: "
+fi
 
-MANAGER_LIST = [
-    PkgManager("apt-get", True,
-        [
-            ["apt-get", "update"],
-            ["apt-get", "upgrade"],
-            ["apt-get", "autoremove"]
-        ]),
-    PkgManager("brew", False,
-        [
-            ["brew", "update"],
-            ["brew", "upgrade"],
-            ["brew", "autoremove"]
-        ]),
-    PkgManager("dnf", True,
-        [["dnf", "upgrade"]]),
-    PkgManager("dfm", False,
-        [
-            ["dfm", "update"],
-            ["dfm", "deploy"]
-        ]),
-    PkgManager("emerge", True,
-        [
-            ["emerge", "--sync"],
-            ["emerge", "--update", "--deep", "--with-bdeps=y", "@world"],
-            ["emerge", "--deepclean"]
-        ]),
-    PkgManager("flatpak", True,
-        [["flatpak", "update"]]),
-    PkgManager("softwareupdate", False,
-        [["softwareupdate", "--verbose", "-lir", "--agree-to-license"]]),
-    PkgManager("nvim", False,
-        [
-            ["nvim", "--headless", "-c", "lua if vim.pack then vim.pack.update() end", "-c", "qa"],
-            ["echo"]
-        ]),
-    PkgManager("pacman", True,
-        [["echo", "Skipped pacman for yay"] if has("yay") else ["pacman", "-Syu"]]),
-    PkgManager("pkg", False,
-        [
-            ["pkg", "upgrade"],
-            ["pkg", "autoclean"]
-        ]),
-    PkgManager("port", False,
-        [
-            ["port", "-v", "selfupdate"],
-            ["port", "-v", "upgrade", "outdated"],
-            ["port", "-v", "uninstall", "inactive"]
-        ]),
-    PkgManager("scoop", False,
-        [["scoop", "update"]]),
-    PkgManager("snap", True,
-        [["snap", "refresh"]]),
-    PkgManager("tldr", False,
-        [["tldr", "-u"]]),
-    PkgManager("yay", False,
-        [["yay", "-Syu", "--noconfirm"]])
-]
+for key in "${toUpdate[@]}" ; do
+    if has "$key" && ! contains "$key" "${toSkip[@]}" ; then
+        if $listMode ; then
+            printf "%s, " "$key"
+        else
+            ok "Updating $key."
+            eval "${MANAGER_LIST[$key]}"
+        fi
+    fi
+done
 
-try:
-    parser = argparse.ArgumentParser(description="a program to automatically update installed package managers")
-
-    parser.add_argument("--toUpdate", dest="toUpdate", help="specify which managers to update", nargs="+", type=str)
-    parser.add_argument("--skip", "-s", dest="skip", help="specify which managers to skip", nargs="+", type=str)
-    parser.add_argument("--list", "-l", dest="listMode", action="store_true", help="list availible package managers")
-    parser.add_argument("--all", "-a", dest="UPDATE_ALL", action="store_true",
-                        help="update all availible package managers, (this is the default)")
-
-    args = vars(parser.parse_args())
-    toUpdate = args["toUpdate"]
-    listMode = args["listMode"]
-    skip = args["skip"]
-    UPDATE_ALL = args["UPDATE_ALL"]
-
-    # remove skipped managers
-    if skip is not None:
-        for skippedManager in skip:
-            if skippedManager in MANAGER_LIST:
-                MANAGER_LIST.pop(skippedManager)
-            else:
-                warn("unrecognized package manager '" + str(skippedManager.keys()) + "'.")
-
-    if listMode:
-        print(get_managers())
-    elif toUpdate is None or UPDATE_ALL:
-        #update all availible packages
-        for manager in MANAGER_LIST:
-            update(manager)
-    else:
-        ok("Updating " + str(toUpdate) + ".")
-        for selectedManager in toUpdate:
-            if selectedManager in MANAGER_LIST:
-                update(selectedManager)
-            else:
-                warn("unrecognized package manager '" + str(selectedManager) + "'.")
-except KeyboardInterrupt:
-    error("KeyboardInterrupt")
+if $listMode ; then
+    printf "\b\b \n"
+fi
